# Generated by Django 6.0.4 on 2026-09-29 14:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('url_adm', models.CharField(help_text='Subdomínio: https://<url_adm>.britech.com.br/PAS', max_length=80)),
                ('segredo_ref', models.CharField(blank=True, help_text='Nome do segredo no cofre. Nunca o valor.', max_length=200)),
                ('max_sessoes', models.PositiveSmallIntegerField(default=1)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disjuntor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200, unique=True)),
                ('aberto_desde', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('falhas_consecutivas', models.PositiveIntegerField(default=0)),
                ('ultimo_erro_tipo', models.CharField(blank=True, max_length=60)),
                ('proxima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('reaberto_por', models.CharField(blank=True, max_length=120)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravaRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200, unique=True)),
                ('dono', models.CharField(max_length=120)),
                ('lease_ate', models.DateTimeField()),
                ('adquirida_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('concluida_com_falhas', 'Concluída com falhas')], default='aberta', max_length=24)),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('ano', 'mes'), name='uniq_competencia_ano_mes')],
            },
        ),
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disparada_por', models.CharField(default='manual', max_length=120)),
                ('escopo', models.JSONField(blank=True, default=dict)),
                ('forcar', models.BooleanField(default=False)),
                ('cascata', models.BooleanField(default=False)),
                ('iniciada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('concluida_com_falhas', 'Concluída com falhas')], default='em_andamento', max_length=24)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='core.competencia')),
            ],
            options={
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_britech', models.CharField(help_text='Id da carteira na Britech', max_length=30)),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', '14 dígitos')])),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('FIF', 'FIF'), ('FIDC', 'FIDC'), ('FII', 'FII'), ('FIP', 'FIP'), ('FIAGRO', 'FIAGRO'), ('FUNCINE', 'FUNCINE'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10)),
                ('exercicio_mes', models.PositiveSmallIntegerField(blank=True, help_text="Mês de encerramento do exercício (define a pasta 'Data Base <mês> <ano>')", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('pasta_drive_id', models.CharField(blank=True, max_length=128)),
                ('monday_item_id', models.CharField(blank=True, max_length=40)),
                ('ativo', models.BooleanField(default=True)),
                ('administradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fundos', to='core.administradora')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EtapaExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('baixar_insumos', 'Baixar insumos'), ('processar_contabil', 'Processar Contábil'), ('baixar_balancete', 'Baixar balancete'), ('popular_excel', 'Popular Excel'), ('publicar_drive', 'Publicar no Drive')], max_length=24)),
                ('fila', models.CharField(help_text='api | browser | excel | drive', max_length=20)),
                ('backend', models.CharField(choices=[('api', 'API'), ('browser', 'Navegador (Playwright)'), ('excel', 'Excel (COM)'), ('drive', 'Drive'), ('fake', 'Fake (testes)')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('sucesso', 'Sucesso'), ('falha', 'Falha'), ('aguardando_britech', 'Aguardando Britech'), ('pulado', 'Pulado')], default='pendente', max_length=20)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('max_tentativas', models.PositiveSmallIntegerField(default=3)),
                ('forcar', models.BooleanField(default=False, help_text='Ignora a idempotência (reprocesso)')),
                ('erro_tipo', models.CharField(blank=True, max_length=60)),
                ('erro_msg', models.TextField(blank=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('disponivel_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('lock_key', models.CharField(blank=True, max_length=120)),
                ('worker_id', models.CharField(blank=True, max_length=120)),
                ('lease_ate', models.DateTimeField(blank=True, null=True)),
                ('aguardando_desde', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='core.execucao')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas', to='core.fundo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('baixar_insumos', 'Baixar insumos'), ('processar_contabil', 'Processar Contábil'), ('baixar_balancete', 'Baixar balancete'), ('popular_excel', 'Popular Excel'), ('publicar_drive', 'Publicar no Drive')], max_length=24)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('sucesso', 'Sucesso'), ('falha', 'Falha'), ('aguardando_britech', 'Aguardando Britech'), ('pulado', 'Pulado')], max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='core.competencia')),
                ('ultima_etapa_execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.etapaexecucao')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='core.fundo')),
            ],
        ),
        migrations.CreateModel(
            name='PastaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_folder_id', models.CharField(max_length=128)),
                ('caminho_relativo', models.CharField(blank=True, max_length=500)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='core.competencia')),
                ('fundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='core.fundo')),
            ],
        ),
        migrations.CreateModel(
            name='Artefato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('insumo_carteira_final', 'Insumo: carteira final'), ('insumo_carteira_inicial', 'Insumo: carteira inicial'), ('insumo_extrato_cc', 'Insumo: extrato conta corrente'), ('insumo_mov_cotista', 'Insumo: movimentação de cotistas'), ('insumo_posicao_cotista_final', 'Insumo: posição de cotistas (final)'), ('insumo_posicao_cotista_inicial', 'Insumo: posição de cotistas (inicial)'), ('insumo_historico_cota', 'Insumo: histórico de cota'), ('balancete_pdf', 'Balancete (PDF)'), ('balancete_xls', 'Balancete (Excel)'), ('boleta', 'Boleta populada'), ('screenshot', 'Screenshot de falha'), ('trace', 'Trace do Playwright'), ('log', 'Log')], max_length=40)),
                ('nome', models.CharField(max_length=300)),
                ('caminho_local', models.CharField(blank=True, max_length=600)),
                ('sha256', models.CharField(max_length=64)),
                ('tamanho_bytes', models.BigIntegerField()),
                ('drive_file_id', models.CharField(blank=True, max_length=128)),
                ('drive_checksum', models.CharField(blank=True, max_length=64)),
                ('verificado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('etapa_execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefatos', to='core.etapaexecucao')),
            ],
            options={
                'indexes': [models.Index(fields=['sha256'], name='core_artefa_sha256_845048_idx'), models.Index(fields=['etapa_execucao', 'tipo'], name='core_artefa_etapa_e_676fcd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='execucao',
            index=models.Index(fields=['competencia', 'iniciada_em'], name='core_execuc_compete_d9ff14_idx'),
        ),
        migrations.AddIndex(
            model_name='fundo',
            index=models.Index(fields=['tipo'], name='core_fundo_tipo_b4722d_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundo',
            constraint=models.UniqueConstraint(fields=('administradora', 'codigo_britech'), name='uniq_fundo_adm_codigo'),
        ),
        migrations.AddIndex(
            model_name='etapaexecucao',
            index=models.Index(fields=['fila', 'status', 'disponivel_em'], name='core_etapae_fila_9b37d8_idx'),
        ),
        migrations.AddIndex(
            model_name='etapaexecucao',
            index=models.Index(fields=['status', 'disponivel_em'], name='core_etapae_status_a68b75_idx'),
        ),
        migrations.AddIndex(
            model_name='etapaexecucao',
            index=models.Index(fields=['lock_key', 'status'], name='core_etapae_lock_ke_6045b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='etapaexecucao',
            constraint=models.UniqueConstraint(fields=('execucao', 'fundo', 'etapa'), name='uniq_etapa_por_execucao_fundo'),
        ),
        migrations.AddConstraint(
            model_name='estadoetapa',
            constraint=models.UniqueConstraint(fields=('fundo', 'competencia', 'etapa'), name='uniq_estado_fundo_comp_etapa'),
        ),
        migrations.AddConstraint(
            model_name='pastacompetencia',
            constraint=models.UniqueConstraint(fields=('fundo', 'competencia'), name='uniq_pasta_fundo_competencia'),
        ),
    ]
