# Generated by Django 6.0.4 on 2026-09-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefato',
            name='tipo',
            field=models.CharField(choices=[('insumo_carteira_final', 'Insumo: carteira final'), ('insumo_carteira_inicial', 'Insumo: carteira inicial'), ('insumo_extrato_cc', 'Insumo: extrato conta corrente'), ('insumo_mov_cotista', 'Insumo: movimentação de cotistas'), ('insumo_posicao_cotista_final', 'Insumo: posição de cotistas (final)'), ('insumo_posicao_cotista_inicial', 'Insumo: posição de cotistas (inicial)'), ('insumo_historico_cota', 'Insumo: histórico de cota'), ('insumo_pdf', 'Insumo: PDF de evidência'), ('balancete_pdf', 'Balancete (PDF)'), ('balancete_xls', 'Balancete (Excel)'), ('boleta', 'Boleta populada'), ('screenshot', 'Screenshot de falha'), ('trace', 'Trace do Playwright'), ('log', 'Log')], max_length=40),
        ),
    ]
