# Generated by Django 6.0.4 on 2026-09-29 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_artefato_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(db_index=True, max_length=160)),
                ('severidade', models.CharField(default='aviso', max_length=10)),
                ('titulo', models.CharField(max_length=250)),
                ('corpo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('canais', models.CharField(blank=True, help_text='canais configurados quando foi gerado', max_length=40)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('erro_envio', models.TextField(blank=True)),
                ('repeticoes', models.PositiveIntegerField(default=0, help_text='ocorrências suprimidas por duplicidade')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
